### ISSUE TITLE
Spatie permissions migration need update

### ISSUE THREAD

**Issue by calvez** [nikspyratos/toybox#2]
Hi, the project is very interesting, I will keep my eye on it.
However right now the migrations need to be updated:
https://spatie.be/docs/laravel-permission/v6/upgrading

**Comment by nikspyratos** [comment]
Thanks for sending this through! Will have a go at upgrading soon.

**Comment by nikspyratos** [comment]
I have now replaced the config & migration with the latest ones 👍
